### ISSUE TITLE
Image data is not freed after being loaded

### ISSUE THREAD

**Issue by cflip** [ComponentFlip/Chromaray#8]
stb_image documentation says to call `stbi_free_image` after loading an image, but since I could not find a way to copy the image data into the struct I removed the `stbi_free_image` call as a temporary fix.

**Comment by jprik** [comment]
yeah!

**Comment by h5p9sl** [comment]
oh no. dont worry im sure there is a way to fix it!

**Comment by jprik** [comment]
MEE TO

**Comment by h5p9sl** [comment]
I fixed it in #10 :1st_place_medal:
